version: '3'
services: 
  elasticsearch:
    build: ./dockerfile/elasticsearch/
    image: ek
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - "../data/elasticsearch:/usr/share/elasticsearch/data"     
    environment:
      - "discovery.type=single-node"  
  kibana:
    build: ./dockerfile/kibana/
    ports:
      - 5601:5601
    volumes:
      - "../data/kibana:/usr/share/kibana/data"  
    depends_on:
      - elasticsearch  
   
  task4wiki:
    build: ./dockerfile/python
    image: task4
    volumes:
      - "../code/:/code/"
    depends_on:
      - elasticsearch
    command: python3 /code/pyelastic.py     
#docker run -d -p 9200:9200 -p 5601:5601 -v "data:/home/elasticsearch/elasticsearch/data" nshou/elasticsearch-kibana      