version: '3.1'

services:
  task3wiki:
    build: .
    image: task3
    volumes:
      - "../code/:/code/"
    depends_on:
      - mongo
    command: python3 /code/task3.py  
  
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"    
    volumes:
      - "./data/:/data/"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd1234
    restart: always  